apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: netsoldier

commonLabels:
  app.kubernetes.io/name: ml-anomaly
  app.kubernetes.io/part-of: netsoldier

resources:
  - serviceaccount.yaml
  - deployment.yaml
  - pdb.yaml
  - models-pvc.yaml
