apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ml-anomaly
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: ml-anomaly
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
