apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kyverno/kyverno/releases/download/v1.12.6/install.yaml
  - policies/verify-image-signatures.yaml
  - policies/require-non-root.yaml
  - policies/require-read-only-root-fs.yaml
  - policies/require-resource-limits.yaml
