apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../base/misp
  - ../../base/clickhouse

commonLabels:
  app.kubernetes.io/instance: proxmox-soc

patches:
  - path: patches/detection-engine-resources.yaml
  - path: patches/device-inventory-resources.yaml
  - path: patches/web-ui-resources.yaml
