apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../base/clickhouse
  - ../../base/minio
  - ../../base/misp
  - ../../base/killswitch-controller
  - ../../base/threat-intel-sync
  - ../../base/ntopng
  - ../../base/suricata
  - ../../base/zeek
  - ../../base/rita
  - ../../base/ml-anomaly

commonLabels:
  app.kubernetes.io/instance: proxmox-soc

patches:
  - path: patches/detection-engine-resources.yaml
  - path: patches/device-inventory-resources.yaml
  - path: patches/web-ui-resources.yaml
  - path: patches/killswitch-controller-resources.yaml
  - path: patches/threat-intel-sync-resources.yaml
