apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-dashboard-cm.yaml
  - grafana-dns-threat-intel-cm.yaml
  - grafana-killswitch-audit-cm.yaml
  - grafana-network-overview-cm.yaml
  - grafana-dpi-protocols-cm.yaml
  - grafana-tls-anomalies-cm.yaml
  - prometheus-rules.yaml
