apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: detection-engine
  app.kubernetes.io/part-of: netsoldier

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - pdb.yaml
