apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: detection-engine
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: detection-engine
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
