apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: netsoldier

commonLabels:
  app.kubernetes.io/name: clickhouse
  app.kubernetes.io/part-of: netsoldier

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - statefulset.yaml
  - service.yaml
  - cold-export-cm.yaml
  - cold-export-cronjob.yaml
