apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: netsoldier

commonLabels:
  app.kubernetes.io/instance: pi-edge

resources:
  - ../../base/namespace.yaml
  - ../../base/detection-engine/
  - ../../base/device-inventory/
  - ../../base/fluent-bit/
  - ../../../adguard/

patches:
  - path: patches/detection-engine-resources.yaml
  - path: patches/device-inventory-resources.yaml
  - path: patches/detection-engine-env.yaml
  - path: patches/fluent-bit-resources.yaml
