apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard-home
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/migel9090/netSoldier.git
    targetRevision: main
    path: deploy/adguard
  destination:
    server: https://kubernetes.default.svc
    namespace: dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
