apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-self.yaml
  - kyverno-app.yaml
  - netsoldier-appset.yaml
  - observability-app.yaml
  - loki-app.yaml
  - alloy-app.yaml
