apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-inventory
spec:
  template:
    spec:
      containers:
        - name: device-inventory
          env:
            - name: CLICKHOUSE_URL
              value: "http://clickhouse.netsoldier.svc:8123"
            - name: CLICKHOUSE_DATABASE
              value: "netsoldier"
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_BIND_SERVICE
                - NET_RAW
              drop:
                - ALL
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
