apiVersion: apps/v1
kind: Deployment
metadata:
  name: killswitch-controller
spec:
  template:
    spec:
      containers:
        - name: killswitch-controller
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
