name: IaC Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '55 3 * * 1'

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Checkov
        uses: bridgecrewio/checkov-action@fa9edf8f0a491c59a924ea6accd5bdcf07752cff # v12.3107.0
        with:
          directory: .
          soft_fail: true
          output_format: sarif
          output_file_path: checkov.sarif
          quiet: true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        if: always()
        with:
          sarif_file: checkov.sarif
          category: checkov

  terraform:
    name: Terraform validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/terraform
    steps:
      - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1

      - name: Format check
        run: terraform fmt -check -recursive

      - name: Init (providers only)
        run: terraform init -backend=false

      - name: Validate
        run: terraform validate

  kics:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: KICS scan
        uses: checkmarx/kics-github-action@05aa5eb70eede1355220f4ca5238d96b397e30a6 # v2.1.20
        with:
          path: .
          fail_on: high
          exclude_paths: "deploy/helm,deploy/argocd/patches,deploy/argocd/*.example.yaml,deploy/kustomize/base/misp,deploy/kustomize/base/detection-engine/secret.example.yaml"
          exclude_queries: "aa8f7a35-9923-4cad-bd61-a19b7f6aac91,5308a7a8-06f8-45ac-bf10-791fe21de46e"
          output_formats: sarif
          output_path: .

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        if: always()
        with:
          sarif_file: results.sarif
          category: kics
